#!/bin/sh
set -e

lb config \
  --mode debian \
  --architectures amd64 \
  --distribution bookworm \
  --binary-images iso-hybrid \
  --debian-installer live \
  --bootloaders "syslinux,grub-efi" \
  --archive-areas "main contrib non-free non-free-firmware" \
  --bootappend-live "boot=live components username=puenteos hostname=puenteos" \
  --iso-application "PuenteOS" \
  --iso-publisher "PuenteOS" \
  --iso-preparer "PuenteOS build" \
  --iso-volume "PuenteOS_1.0"
